New input
enzo-project/enzo-e pull request #175
Opened 2022-05-09 03:11 UTC by jobordner

This branch implements scalable checkpoint / restart, and allows for changing parameters and numbers of processors on restart. It's another huge PR, sorry about that.

Example test files are in `input/Checkpoint/test_cosmo-[check|restart].in`, which run the DD cosmology test as usual to cycle 160, but writes a checkpoint directory at cycle 140 and restarts from that. 

This is scalable: it works by generating a Morton curve ordering of blocks, and assigning blocks to `IoWriter` (for checkpoint) or `IoReader` (for restart) chare array elements, which handle concurrent I/O. No parallel HDF5 (yet), but checkpoint has been tested on 212992 cores writing 4096 files.

There are some remaining issues to clean up, hence the "draft pull request". Including but not necessarily limited to:

1. finishing documentation
2. fixing some memory leaks
3. more thorough testing
4. integrating the `"order"` method into the `"check"` method
5. cleaning up code a bit

2022-06-10 18:26 UTC, peeples commented
@jobordner What is the current status of this, as it is one of the current highest priority items? In particular, would it be possible for people to start reviewing it now, with some of the other items (e.g., documentation, the code cleanup) as part of another, smaller, later PR?

2022-06-11 14:08 UTC, jobordner commented
> 

@peeples Sure, it's usable though there are some remaining code issues (e.g. memory leak).

2022-06-16 16:01 UTC, jwise77 requested changes
Because this was out of my wheelhouse, I could only do a superficial review of the code. I made several suggestions and questions in the code -- no development blockers, just some clarification and additional documentation.

2022-06-16 16:47 UTC, jobordner commented on input/test_cosmo.incl
> +     redshift = -50.0;
This was a temporary change for testing something out that got inadvertently checked in. Reverted.

2022-06-17 14:29 UTC, mabruzzo approved these changes
I took a quick look through all of the files. I left a few small comments, but it generally looks good to me. The documentation looks like it needs a little more work. But, maybe it makes sense to merge sooner?

At some point we really need to document all of the output parameters on the webpage. I suppose it will make sense to do this for `EnzoMethodOutput` and `EnzoMethodCheck`, when we finally rip off the band-aid and remove the old output method.

Do I understand correctly that `EnzoMethodOutput` and `EnzoMethodCheck` use different strategies for assigning blocks to data files? If so, is the long-term intention to unify these strategies or keep them different?

2022-06-21 18:22 UTC, mabruzzo commented on src/Enzo/enzo_control_restart.cpp
> +    io->meta_value(i,& buffer, &name, &type_scalar, &nx,&ny,&nz);
```suggestion
```
I think you can delete these lines

2022-06-21 19:58 UTC, jobordner commented
> Do I understand correctly that `EnzoMethodOutput` and `EnzoMethodCheck` use different strategies for assigning blocks to data files? If so, is the long-term intention to unify these strategies or keep them different?

The intention is to unify them, such that `EnzoMethodOutput` uses the `EnzoMethodCheck` approach.

2022-06-21 20:16 UTC, jobordner commented on src/Enzo/enzo_control_restart.cpp
> +  // [ Called on root ip only ]
my convention for variable storing process id; will clarify

2022-06-21 20:21 UTC, jobordner commented on src/Enzo/enzo_control_restart.cpp
> +    }
Will remove, this case is not needed.

2022-06-23 17:13 UTC, jobordner commented on src/Cello/io_IoFieldData.cpp
> +  INCOMPLETE("IoFieldData::save_to()");
This is not needed--removed.

2022-06-23 17:49 UTC, jobordner commented on src/Enzo/enzo-e.cpp
> +  if (PARALLEL_ARGC > 2 && strcmp(PARALLEL_ARGV[2],"-dryrun")==0) {
added usage printf

2022-06-28 17:36 UTC, jobordner commented on doc/source/design/design-input.rst
> +// EnzoBlocks. Replaces functionality of control_adapt.
Agreed; done.

2022-06-29 22:31 UTC, jwise77 approved these changes
Thanks for addressing my comments. I'm approving, but before merging, there are some conflicts that need to be fixed.

2022-06-30 20:25 UTC, peeples commented
@jobordner looks like this is ready to go, modulo the conflicts (from @brittonsmith's new answer tests?). Can we get this through in time for a July 1 v1.0 release?

2022-07-01 19:00 UTC, merged