Clarify how to specify libpng installation path.
enzo-project/enzo-e pull request #204
Opened 2022-06-13 11:47 UTC by mabruzzo

Clarifying that you would use `-DPNG_ROOT` instead of `-DLIBPNG_ROOT`

2022-06-13 13:47 UTC, peeples approved these changes

2022-06-14 15:03 UTC, jwise77 requested changes
It wasn't introduced by you but just a small grammar correction.

2022-06-14 15:03 UTC, jwise77 commented on doc/source/tutorial/getting_started.rst
> +* these package location are also picked up from the environment, i.e., an alternative option  is ``export <package_name>_ROOT=/PATH/TO/PACKAGE/INSTALL`` .
```suggestion
* these package locations are also picked up from the environment, i.e., an alternative option  is ``export <package_name>_ROOT=/PATH/TO/PACKAGE/INSTALL`` .
```

2022-06-14 15:39 UTC, gregbryan approved these changes

2022-06-14 16:15 UTC, jwise77 approved these changes

2022-06-14 16:16 UTC, merged