Nested initial grids - WIP
enzo-project/enzo-e pull request #285
Opened 2023-02-26 23:36 UTC by brenjohn

### Overview
Added some infrastructure to facilitate nested initial grids: 
 - Member functions were added to Cello and EnzoE Block classes. These can be used to check if a block should refine during the initialization phase and to create the child blocks if it should.
 - Helper classes were introduced to the EnzoInitialHdf5 files called DataLoaders. These were introduced to facilitate reading HDF5 data for blocks on different levels and to avoid introducing further code duplication.
 - The Config, Parameter and Hierarchy classes were updated to read and store parameters from the parameter file regarding nested initial grids. 

### Details
The following changes were made to the input parameter file to read in nested initial grids:
 - A level parameter was introduced to the file groups within the HDF5 group to indicate which level the HDF5 file contains data for.
 - Lower and Upper parameters where added to the Mesh group for each level of the initial grid. These define a region of parent blocks on level `L-1` which need to refine to create the nested grid at level `L`.
 - The `max_level` parameter in the HDF5 group is used to only initialize levels up to level `max_level`.

2023-06-21 19:30 UTC, fearmayo approved these changes

2023-10-08 16:42 UTC, mabruzzo commented
If it's not too much trouble, it probably makes sense to do a rebase so that the ics aren't in the commit history (let me know if you need some help with how to do that).

If we choose not to do that, then the ics will inflate the size of the repository as we move forward.

2023-10-08 16:52 UTC, brenjohn commented
You read my mind! :P 

I was just looking into ways to remove the ics from the commit history. I also planned on doing a rebase anyway to take in new changes from main. I'll be in touch if I get stuck.

I was thinking the same about an enzo-project repository for files like these and was going to bring it up in the next meeting. I don't think what I've done here is ideal long term. I was thinking maybe a data directory in the top level of enzo-e which we could turn into a git submodule might make sense but we should discuss this first and would go in its own PR.

2024-03-25 19:45 UTC, jobordner requested changes
Overall this looks great! 

While I don't expect it to be used for 2D problems, Enzo-E does explicitly support rank < 3, so I would add something to the documentation stating this is implemented for 3D only, and maybe add an ASSERT to check that.

 I also didn't see a reference to cycle in `refine_during_initialization()`, which I'm guessing could be an issue if for example the initialially refined blocks are coarsened in some later cycle(?)

Nice work!

2024-03-25 19:45 UTC, jobordner commented on .circleci/config.yml
The IC's for the test problem should probably be brought into the input directory to avoid referencing external projects.

2024-03-25 19:45 UTC, jobordner commented on doc/source/param/mesh.incl
To help avoid confusion about "level_n_lower" and "level_n_upper" being the literal parameter names, I'd update the markup to something like
```
:Parameter:  :p:`Mesh` : :p:`level_`:g:`<n>`:p:`_lower`
```
A short example could also be helpful.

2024-03-25 19:45 UTC, jobordner commented on src/Cello/mesh_Block.cpp
`index_from_global(ix,iy,iz, nx,ny,nz, ax,ay,az)` can be removed since it's never called

2024-05-15 14:19 UTC, brenjohn commented
Thanks @jobordner

I think I've addressed everything now. Let me know if there's anything else.

Just regarding the comment about initial blocks possibly coarsening at a later cycle. From what I understand this would be intended behavior and we want blocks to coarsen if they can, even if they were part of an initially refined region. The increased particle resolution should still be there, possibly in some other block.

2024-05-30 20:16 UTC, jwise77 commented
@jobordner Can you review John B's recent changes that addressed your comments? If all looks good, please go ahead and approve. Thanks!

2024-06-04 22:45 UTC, jobordner approved these changes

2024-06-04 23:08 UTC, merged