Suppress warnings charm++ module headers
enzo-project/enzo-e pull request #298
Opened 2023-03-23 17:30 UTC by mabruzzo

This PR builds directly on PR #272 (it shouldn't be merged until afterwards).

This PR takes steps to suppress compiler warnings in the header files generated by ``charmc`` from ``.ci`` (these warnings are really just noise -- we can't do much about them without altering charm++). 

This is essentially done by telling the compiler to treat them like system headers with the (i.e. passing the `-isystem` flag to `gcc` or `clang` -- this may not suppress warnings on all compilers, but it's a good start)

In more detail, we now:
1. place the headers generated by ``charmc`` from ``.ci`` files into their own sub-directories -- a subdirectory is automatically made for headers generated from the ``ci`` files from the ``Cello``-layer and another is created for the headers generated from the ``ci`` file from the ``Enzo``-layer.
2. label all headers in these subdirectories as system-headers.

2023-07-02 20:35 UTC, gregbryan requested changes
A couple of typos that need to be fixed, otherwise good.

2023-07-02 20:35 UTC, gregbryan commented on cmake/charm.cmake
> +# ``SUPRESS_CHARM_HEADER_WARNING`` global variable with a value of ``0``.
```suggestion
# ``SUPPRESS_CHARM_HEADER_WARNING`` global variable with a value of ``0``.
```

2023-07-02 20:35 UTC, gregbryan commented on cmake/charm.cmake
> +  if(SUPRESS_CHARM_HEADER_WARNING OR NOT DEFINED SUPRESS_CHARM_HEADER_WARNING)
```suggestion
  if(SUPPRESS_CHARM_HEADER_WARNING OR NOT DEFINED SUPPRESS_CHARM_HEADER_WARNING)
```

2023-07-08 14:49 UTC, mabruzzo commented on cmake/charm.cmake
> +# ``SUPRESS_CHARM_HEADER_WARNING`` global variable with a value of ``0``.
Fixed

2023-07-08 14:49 UTC, mabruzzo commented on cmake/charm.cmake
> +  if(SUPRESS_CHARM_HEADER_WARNING OR NOT DEFINED SUPRESS_CHARM_HEADER_WARNING)
Fixed

2024-02-20 16:54 UTC, mabruzzo commented
This is one of the PRs where we decided that we only needed 1 approval and Greg signed off on it (even though he never explicitly hit approve), so I'm merging.

2024-02-20 16:55 UTC, merged