Updating Hydro routines round 2
enzo-project/enzo-e pull request #48
Opened 2020-06-11 18:51 UTC by aemerick

Finalizing renaming and moving of redundant hydro routines that did not
    get fixed in prior PPM-cull PR. This moves and renames all woc_thing.F
    routines to thing.F, and removes the previous thing.F files. The previous
    thing.F files were originally named thing_dev.F before the recent PPM-cull
    PR. It appears the woc_thing.F files are more recent than the thing_dev.F
    files were, as the woc_thing.F files show fewer differences with their
    equivalents in Enzo.
    
    enzo_EnzoMethodHydro is retained (the routine that called the woc_thing.F routines)
    but commented out entirely to avoid confusion with the current PPM and
    SolveHydroEquations methods... This has not been removed entirely in case
    development continues here (this was originally a way to refactor and improve
    the way thigns are currently done in SolveHydroEquations).

2021-01-08 20:28 UTC, jwise77 requested changes
This all looks good! However there are a bunch of conflicts, presumably arising after the dd merge. Fix these and I'll approve.

2021-01-15 18:19 UTC, bwoshea commented
@aemerick lots of merge conflicts here... This looks easy to fix, at least.

2021-01-20 22:57 UTC, mabruzzo approved these changes
This all looks good to me.

2021-01-20 22:57 UTC, mabruzzo commented on src/Enzo/enzo_EnzoMethodHydro.cpp
> +// This is not used, but is a starting point to refactor current
Great, I'm really happy to see this. I found the `EnzoMethodHydro` method to be really confusing when I was first getting acquainted with the codebase.

2021-05-20 12:24 UTC, jwise77 commented
I will fix the conflicts today.

2021-05-21 18:08 UTC, jwise77 approved these changes
Fixed conflicts, and I will merge once the tests pass.

2021-05-21 19:18 UTC, merged